import { poppins } from "@/utils/fonts";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={poppins.className}>
          <Navbar />
          <Toaster />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
