import "../../../globals.css";
import LeftNavbar from "./LeftNavbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="grid grid-cols-[20%,80%]">
      <div className="">
        <LeftNavbar />{" "}
      </div>
      <div className=""> {children}</div>
    </div>
  );
}
