import AuthProvider from "@/providers/AuthProvider";
import "../globals.css";
import { poppins } from "@/utils/fonts";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Toaster />

        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
